### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by DreamerLuu** [multimediaFor/ConvNeXtFF#3]
Hello author, I admire your work very much and try to reproduce your experiment to some extent, but your experimental code is too complicated, could you tell me about the structure of the code, for example, there are many backbone

**Comment by multimediaFor** [comment]
Hello! You can refer to the official MMSegmentation documentation for the code structure. Our network configurations are reflected in the 'configs/convnext', which can serve as the entry point for understanding the structure and organization of the code. Hope this helps!
